### PR TITLE
Add comments, Readme, etc.

### PR DESCRIPTION
**Pull request by ThahaShahzad**
please review

### CODE REVIEW

**Comment by farrukhshahzad** [comment]
Looks good. Can you just return 3 decimal places for Std dev. like 2.345?

**Comment by farrukhshahzad** [comment]
use routes like '/std' and '/summation' for micro-service

**Comment by farrukhshahzad** [comment]
Use path instead of params in API routes.

**Review by A-Baji — APPROVED** [review]

**Comment by farrukhshahzad** [comment]
We need to close this PR

**Pull request closed without merging**
